# fly.toml app configuration file generated for beamring on 2023-07-09T19:47:39-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "beamring"
primary_region = "iad"
kill_signal = "SIGTERM"
kill_timeout = "5s"

[experimental]
  auto_rollback = true

[env]
  PHX_HOST = "beamring.io"
  PORT = "8080"
  PRIMARY_REGION = "iad"

[[services]]
  protocol = "tcp"
  internal_port = 8080
  processes = ["app"]

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]
  [services.concurrency]
    type = "connections"
    hard_limit = 1000
    soft_limit = 1000

  [[services.http_checks]]
    interval = 10000
    grace_period = "5s"
    method = "get"
    path = "/"
    protocol = "http"
    restart_limit = 0
    timeout = 2000
    tls_skip_verify = false
